// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package gui

import (
	_ "embed"
	"fyne.io/fyne/v2"
)

//go:embed NotoSansEthiopic.ttf
var resourceNotoSansEthiopicTtfData []byte
var resourceNotoSansEthiopicTtf = &fyne.StaticResource{
	StaticName:    "NotoSansEthiopic.ttf",
	StaticContent: resourceNotoSansEthiopicTtfData,
}
