package gui

// Generated by: fyne bundle -o bundled.go NotoSansEthiopic.ttf

import (
	"image/color"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/theme"
)

// ethioTheme uses a font with Ethiopic script support for Amharic rendering.
type ethioTheme struct{}

func (e ethioTheme) Color(name fyne.ThemeColorName, variant fyne.ThemeVariant) color.Color {
	return theme.DefaultTheme().Color(name, variant)
}

func (e ethioTheme) Icon(name fyne.ThemeIconName) fyne.Resource {
	return theme.DefaultTheme().Icon(name)
}

func (e ethioTheme) Font(style fyne.TextStyle) fyne.Resource {
	// Fall back to default for monospace since the bundled font is proportional.
	if style.Monospace {
		return theme.DefaultTheme().Font(style)
	}
	// NotoSansEthiopic is a variable font covering regular and bold weights.
	return resourceNotoSansEthiopicTtf
}

func (e ethioTheme) Size(name fyne.ThemeSizeName) float32 {
	return theme.DefaultTheme().Size(name)
}
